#!/usr/bin/env bash
# setup my server; install nginx; configure server to return string "Hello World!"
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

/etc/init.d/nginx restart

