#!/usr/bin/env bash
# setup my server; install nginx; configure server to return string "Hello World!"
# configure nginx to redirect to another enpouint when visiting the path /redirect_me.
# Also return an error code of 301, moved permanently.

apt-get -y update;
apt-get -y install nginx;
ufw allow 'Nginx HTTP';
echo 'Hello World!' > /var/www/html/index.nginx-debian.html;
echo "Ceci n'est pas une page" > /var/www/html/404.html;

# Backup file before modification
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

sed -i '0,/location \/ {/s/location \/ {/location \/redirect_me { \n \t\treturn 301 https:\/\/www.youtube.com;\n\t}\n\tlocation \/ {/' /etc/nginx/sites-available/default

sed -i '0,/location \/ {/s/location \/ {/error_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}\n\tlocation \/ {/' /etc/nginx/sites-available/default;

/etc/init.d/nginx restart
# OR
# service nginx restart
# OR
# nginx -s reload
