#!/usr/bin/env bash
# My script is sending a file to my ubuntu server


# download private key
curl -o zebra https://fv5-3.failiem.lv/down.php?i=a32d8su9ki
echo "I an testing the alxse security network" > vulnerable;


ssh -i ssh_key ubuntu@100.25.164.42 'echo "my ip" > hacked'

# scp -o StrictHostKeyChecking=no -i zebra vulnerable ubuntu@100.25.164.42:~/ 


