#!/usr/bin/env bash
# installs HaProxy on a new ubuntu server machine


# ~~~~~~~~~~~ Installing HAproxy
sudo apt update -y && sudo apt upgrade -y

sudo apt -y install --no-install-recommends software-properties-common

sudo add-apt-repository -y ppa:vbernat/haproxy-2.4

sudo apt -y install haproxy=2.4.\*

# Installing HAproxy ~~~~~~~~~~~~


# ~~~~~~~~~~~ Configure HAproxy
# First configure Haproxy to have a frontend (frontend myfrontend
#                                                       bind 0.0.0.0:80)
# Create a backend which contains a list of servers. You can also create
# a special case on the front end to determin which backend to route your requests to

# Create a backup
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

echo -e "\nfrontend frontend1\n\tbind *:80\n\tmode http" >> /etc/haproxy/haproxy.cfg
echo -e "\tdefault_backend myservers" >> /etc/haproxy/haproxy.cfg
echo -e "\nbackend myservers\n\tbalance roundrobin\n\tserver 298743-web-01 100.25.164.42:80 check\n\tserver 298743-web-02 54.237.74.8:80 check" >> /etc/haproxy/haproxy.cfg

echo -e "ENABLED=1" >> /etc/default/haproxy

# Configure HAproxy ~~~~~~~~~~~

# ~~~~~~~~~~~~~~~~~ Restart HAproxy
service haproxy restart
# systemctl restart haproxy
# Restart HAproxy ~~~~~~~~~~~~~~~~~

