#!/usr/bin/env bash
# configure a nginx web server to send a custom header in it's response

# Backup file before modification
cat /etc/nginx/sites-available/default >> /etc/nginx/sites-available/default.backup

mod_str=\"/server_name _;/a \\\n\\tadd_header X-Served-By $(hostname);\"

sed -i $mod_str /etc/nginx/sites-available/default

/etc/init.d/nginx restart
# OR
# service nginx restart
# OR
# nginx -s reload