#!/usr/bin/env bash
# echos 'I an invincible!!!' everytime the script
# encounters a SIGTERM signal
handle_sigterm(){
	echo "I am invincible!!!"
}
trap handle_sigterm SIGTERM
while (( 1 == 1 ))
do
	echo "To infinity and beyond"
	sleep 2
done
