#!/usr/bin/env bash
# works with loops and conditionals in bash
i=1
while [ $i -le 10 ]
do
	if [ $i = 4 ]; then
		echo "bad luck"
	elif [ $i = 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
