#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes
hour=0
minute=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	while [ $minute -le 59 ]
	do
		echo $minute
		((minute++))
	done
	((minute=0))
	((hour++))
done
