#!/usr/bin/env bash
# changes the ip address of localhost and facebook.com

echo "127.0.0.2	localhost" | sudo tee -a /etc/hosts > /dev/null

echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
