#!/usr/bin/env bash
# Changes the user nginx web server is run as
# kill "$(ps auxff | pgrep nginx | head -n 1)"
pkill nginx
chmod 644 /etc/nginx/nginx.conf
sed -i '/user/s/.*/user nginx;/' /etc/nginx/nginx.conf
sed -i '0,/listen \[::\]:80/s/listen \[::\]:80/listen \[::\]:8080/' /etc/nginx/sites-available/default
su nginx -s /bin/bash -c 'service nginx restart'
